[2023-04-14 15:00:11,926] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-14T14:10:00+00:00 [queued]>
[2023-04-14 15:00:12,214] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-14T14:10:00+00:00 [queued]>
[2023-04-14 15:00:12,228] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 15:00:12,246] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-04-14 15:00:12,261] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 15:00:12,578] {taskinstance.py:1089} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-14T14:10:00+00:00
[2023-04-14 15:00:12,660] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2023-04-14 15:00:12,693] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_final_dag', 'create_table', '2023-04-14T14:10:00+00:00', '--job-id', '106', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmpjs04lrzy', '--error-file', '/tmp/tmpggvx3jvl']
[2023-04-14 15:00:12,708] {standard_task_runner.py:77} INFO - Job 106: Subtask create_table
[2023-04-14 15:00:13,961] {logging_mixin.py:104} INFO - Running <TaskInstance: spotify_final_dag.create_table 2023-04-14T14:10:00+00:00 [running]> on host 75651b8604e6
[2023-04-14 15:00:14,679] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_final_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T14:10:00+00:00
[2023-04-14 15:00:14,695] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS top_songs (
            id SERIAL PRIMARY KEY,
            song_date VARCHAR(200),
            song_name VARCHAR(200),
            artist_name VARCHAR(200)
            )
[2023-04-14 15:00:14,835] {base.py:78} INFO - Using connection to: id: postgre_sql. Host: postgres, Port: 5050, Schema: suppliers, Login: airflow, Password: XXXXXXXX, extra: None
[2023-04-14 15:00:14,867] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "postgres" (172.19.0.2) and accepting
	TCP/IP connections on port 5050?

[2023-04-14 15:00:14,883] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=create_table, execution_date=20230414T141000, start_date=20230414T150011, end_date=20230414T150014
[2023-04-14 15:00:15,217] {local_task_job.py:146} INFO - Task exited with return code 1
