[2023-04-14 04:01:08,638] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-14T04:00:01.136419+00:00 [queued]>
[2023-04-14 04:01:08,726] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-14T04:00:01.136419+00:00 [queued]>
[2023-04-14 04:01:08,728] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 04:01:08,729] {taskinstance.py:1069} INFO - Starting attempt 2 of 2
[2023-04-14 04:01:08,730] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 04:01:08,780] {taskinstance.py:1089} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-14T04:00:01.136419+00:00
[2023-04-14 04:01:08,796] {standard_task_runner.py:52} INFO - Started process 69 to run task
[2023-04-14 04:01:08,811] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_final_dag', 'create_table', '2023-04-14T04:00:01.136419+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmpa9aby12z', '--error-file', '/tmp/tmpfvmfb4nd']
[2023-04-14 04:01:08,813] {standard_task_runner.py:77} INFO - Job 18: Subtask create_table
[2023-04-14 04:01:08,929] {logging_mixin.py:104} INFO - Running <TaskInstance: spotify_final_dag.create_table 2023-04-14T04:00:01.136419+00:00 [running]> on host e5626d27743b
[2023-04-14 04:01:09,036] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_final_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T04:00:01.136419+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-14T04:00:01.136419+00:00
[2023-04-14 04:01:09,037] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS top_song(
            song_name VARCHAR(200),
            artist_name VARCHAR(200),
            timestamp VARCHAR(200)
        )
        
[2023-04-14 04:01:09,064] {base.py:78} INFO - Using connection to: id: postgre_sql. Host: postgres, Port: 5432, Schema: spotify_db, Login: airflow, Password: XXXXXXXX, extra: None
[2023-04-14 04:01:09,069] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "spotify_db" does not exist

[2023-04-14 04:01:09,077] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=create_table, execution_date=20230414T040001, start_date=20230414T040108, end_date=20230414T040109
[2023-04-14 04:01:09,342] {local_task_job.py:146} INFO - Task exited with return code 1
